Fatal error: exception Failure("nothing may follow a continue")